printWidth: 80
tabWidth: 2
semi: true
singleQuote: true
trailingComma: es5
bracketSpacing: true
arrowParens: always
htmlWhitespaceSensitivity: ignore
overrides:
  - files: '*.css'
    options:
      # Effectively disables line wrapping so CSS declarations stay on a single
      # line; line breaks in stylesheets are managed by stylelint rules instead.
      printWidth: 500
      singleQuote: false
